name: Branch Protection

on:

  push:

    branches:

      - develop

      - 'feature/**'

      - 'release/**'

  pull_request:

    branches:

      - main

      - develop

jobs:

  branch-protection:

    runs-on: ubuntu-latest

    

    steps:

    - uses: actions/checkout@v4

      with:

        fetch-depth: 0

    

    - name: Setup Node.js

      uses: actions/setup-node@v4

      with:

        node-version: '18'

        cache: 'npm'

    

    - name: Validate branch name

      run: |

        BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

        if [[ "$BRANCH_NAME" == "main" ]]; then

          echo "Direct pushes to main branch are not allowed"

          exit 1

        fi

        if [[ "$BRANCH_NAME" == "develop" && "$GITHUB_EVENT_NAME" == "push" ]]; then

          echo "Checking develop branch push"

        fi

        if [[ "$BRANCH_NAME" =~ ^feature/ ]]; then

          echo "Feature branch detected"

        fi

        if [[ "$BRANCH_NAME" =~ ^release/ ]]; then

          echo "Release branch detected"

        fi

    

    - name: Install dependencies

      run: npm ci

    

    - name: Run all checks

      run: |

        npm run lint

        npm run build

        npm run test --if-present

    

    - name: Check conventional commits

      uses: webiny/action-conventional-commits@v1.1.0

      with:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        

    - name: Check branch is up to date

      run: |

        git fetch origin develop

        BEHIND=$(git rev-list HEAD..origin/develop --count)

        if [ $BEHIND -gt 0 ]; then

          echo "Branch is behind develop by $BEHIND commits. Please update your branch"

          exit 1

        fi
