name: PR Checks

on:

  pull_request:

    branches: [ main ]

jobs:

  validate:

    runs-on: ubuntu-latest

    

    steps:

    - uses: actions/checkout@v4

    

    - name: Setup Node.js

      uses: actions/setup-node@v4

      with:

        node-version: '18'

        cache: 'npm'

        

    - name: Install dependencies

      run: npm ci

      

    - name: Check Types

      run: npm run typecheck || npm run tsc

      

    - name: Lint

      run: npm run lint

      

    - name: Check formatting

      run: npm run format:check || npm run prettier:check || echo "No format check configured"

      

    - name: Build

      run: npm run build

      

    - name: Run Tests

      run: npm run test --if-present

      

    - name: Check bundle size

      uses: preactjs/compressed-size-action@v2

      with:

        repo-token: ${{ secrets.GITHUB_TOKEN }}
